apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: tz65sypip-python 
  janus-idp.io/tekton: tz65sypip-python
  backstage.io/kubernetes-id: tz65sypip-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: tz65sypip-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml